version: '3.9'

services:
  client:
    container_name: client-app
    image: praga-client
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    restart: always
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
    networks:
      - praga
  server:
    container_name: server-app
    image: praga-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      SERVER_PORT: ${SERVER_PORT}
    networks:
      - praga
  postgres:
    container_name: postgress
    image: postgres:latest
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - praga
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: praga@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: praga
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8080:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - praga

volumes:
  db:
  pgadmin:

networks:
  praga:
    driver: bridge
