ARG NODE_VERSION=18
ARG CLIENT_PORT=3000

FROM node:$NODE_VERSION-buster AS builder
WORKDIR /app
COPY package.json yarn.lock
COPY . .
RUN yarn lerna bootstrap
RUN rm -rf /app/packages/client/dist/ && yarn build --scope=client

FROM nginx:latest as production
WORKDIR /app
COPY --from=builder /app/packages/client/dist/ /app/
COPY --from=builder /app/packages/client/nginx.conf /etc/nginx/nginx.conf

EXPOSE $CLIENT_PORT
CMD [ "nginx", "-g", "daemon off;" ]
