ARG NODE_VERSION=18
ARG SERVER_PORT=3001

FROM node:$NODE_VERSION-buster as builder
WORKDIR /app
COPY . .
RUN yarn lerna bootstrap
RUN rm -rf /app/packages/server/dist/ && yarn build --scope=server

FROM node:$NODE_VERSION-buster-slim as production
WORKDIR /app
COPY --from=builder /app/packages/server/dist/ /app/
RUN yarn install --production=true

EXPOSE $SERVER_PORT
CMD [ "node", "/app/index.js" ]
