version: '3.9'

services:
  app:
    container_name: praga-app
    build:
      context: .
      target: production
    restart: always
    expose:
      - '${SERVER_PORT}'
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      POSTGRES_HOST: postgres
    networks:
      - praga
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    expose:
      - '${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - praga
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: praga@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: praga
      PGADMIN_LISTEN_PORT: 8080
    expose:
      - '8080'
    ports:
      - '8080:8080'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - praga

volumes:
  db:
  pgadmin:

networks:
  praga:
    driver: bridge
